CONFIG = {
    'data_path': './data/',
    'raw_data_path': './data/raw/',
    'processed_data_path': './data/processed/',
    'others_data_path': './data/others/',
    'temp_data_path': './data/temp/',
    'idrpr_temp_path' : './data/temp/idrpr/',
    'idrpr_processed_path' : './data/processed/idrpr/',
    'idrpr_others_path' : './data/others/idrpr/',
    'adapar_others_path' : './data/others/adapar/',
    'inmet_raw_path' : './data/raw/inmet/',
    'inmet_processed_path' : './data/processed/inmet/',
    'inmet_temp_path' : './data/temp/inmet/',
    'embrapa_raw_path' : './data/raw/embrapa/',
    'embrapa_others_path' : './data/others/embrapa/',
    'conab_raw_path' : './data/raw/conab/',
    'conab_temp_path' : './data/temp/conab/',
    'sigef_raw_path' : './data/raw/sigef/',
    'sigef_processed_path' : './data/processed/sigef/',
}